name: Build and deploy
on: [push]

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        run: deno task build --dest dist/_out

      - run: cp -r .github/server dist/

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: andreubotella-com
          entrypoint: server/main.ts
          root: dist
